language: minimal
sudo: required
services:
  - docker
before_script:
  - tag="${TRAVIS_TAG:-latest}"
  - image_name="$(echo "${TRAVIS_REPO_SLUG}" | cut -d '/' -f 2)"
  - docker_org="actions"
script: .travis/build.sh $docker_org $tag
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  - provider: script
    script: .travis/deploy.sh $docker_org $tag
    on:
      branch: master
  - provider: script
    script: .travis/deploy.sh $docker_org $tag
    on:
      branch: master
      tags: true
env:
  - MAJOR_VERSION=2 MINOR_VERSION=7 PATCH_VERSION=15 BUILD_ARGS="MAJOR_VERSION MINOR_VERSION PATCH_VERSION"
  - MAJOR_VERSION=3 MINOR_VERSION=6 PATCH_VERSION=5 BUILD_ARGS="MAJOR_VERSION MINOR_VERSION PATCH_VERSION"
  - MAJOR_VERSION=3 MINOR_VERSION=7 PATCH_VERSION=0 BUILD_ARGS="MAJOR_VERSION MINOR_VERSION PATCH_VERSION"